# change the followings to match your Github username and repo name
baseurl: "" # the name of your github repo
url: "https://pablovallejo.github.io" # the url of your github pages

# site information used in page title, meta data etc.
title: "Engineering Manager and Cyclist"
description: About page for Pablo Vallejo

# color theme for links
theme-color: indigo # indigo|yellow|pink|green|stone|

# homepage information
author: Pablo Vallejo
author-bio: Lorem ipsum  # change to false to hide
author-image: 279.jpg  # file must be in the /assets/img/ folder

# navigation menu
show-nav-menu: false

nav-menu:
- text: About
  permalink: about
- text: Bitcoin
  permalink: bitcoin
- text: Blog
  permalink: blog

# use false to turn off any social media links
twitter: false
facebook: false
instagram: https://instagram.com/vallejo_pablo
github: false
linkedin: false
medium: false
google-scholar: false
email: false

# footer information
footer-msg: ""
footer-msg-link: /

# google analytics
google-analytics: G-WCRC1TC2V5

# jekyll plugins - no need to change
plugins:
    - jekyll-seo-tag
